// Generated by CoffeeScript 1.3.3
/*
jQuery scrollUp
(c) 2012 Filip Stefansson, @filipstefansson
Adds an arrow that takes the user to the top of the screen again.
*/(function(){ $ = jQuery; $.extend({scrollUp:function(e){var t,n,r,i;n=$.extend({location:"right",image_src:"img/arrow_up.png",wait:200,time:300},e);n.location==="right"?i="right: 20px;":i="left: 10px;";r="display: none; opacity: .9; filter:alpha(opacity=90); position: fixed; bottom: 10px; "+i;t='<a href="'+n.anchor+'" style="'+r+'" id="scrollUp_arrow"><img src="'+n.image_src+'" alt=""/></a>';$("body").append(t);$(document).scroll(function(){return $(document).scrollTop()>=n.wait?$("#scrollUp_arrow").stop(!0,!0).fadeIn(400):$("#scrollUp_arrow").fadeOut(200)});return $("#scrollUp_arrow").click(function(){$("html, body").animate({scrollTop:0},n.time);return!1})}})}).call(this);